set shell := ['bash', '-ceuo', 'pipefail']

@default: run

@configure:
    mkdir -p cpp/build; \
    cd cpp/build; \
    cmake -GNinja ..

@generate:
    cd model && yardl generate

@build: generate configure
    cd cpp/build && ninja

@run: run-cpp run-python

@run-cpp: build
    echo "-------- C++ demo --------"; \
    ./cpp/build/demo;

@run-python: generate
    echo "-------- Python demo --------"; \
    python python/main.py
